### ISSUE TITLE
Exceptions on clean shutdown

### ISSUE THREAD

**Issue by luceatnobis** [gawel/irc3#104]
As we briefly discussed on IRC, passing SIGINT or calling `self.bot.SIGINT()` exits irc3 uncleanly.

> ERROR asyncio    Task was destroyed but it is pending!
> task: \>Task pending coro=\>process_queue() running at /home/brotherBox/venv/lib/python3.4/site-packages/irc3-0.9.3.dev0-py3.4.egg/irc3/__init__.py:209> wait_for=\>Future finished result=None>>
> Exception ignored in: \>bound method _UnixSelectorEventLoop.__del__ of \>_UnixSelectorEventLoop running=False closed=True debug=False>>
> Traceback (most recent call last):
>   File "/home/brotherBox/venv/lib/python3.4/site-packages/asyncio-3.4.4-py3.4.egg/asyncio/base_events.py", line 431, in __del__
>   File "/home/brotherBox/venv/lib/python3.4/site-packages/asyncio-3.4.4-py3.4.egg/asyncio/unix_events.py", line 58, in close
>   File "/home/brotherBox/venv/lib/python3.4/site-packages/asyncio-3.4.4-py3.4.egg/asyncio/unix_events.py", line 139, in remove_signal_handler
> TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

I run irc3 in a virtual env, running with the following packages:
> asyncio==3.4.4
> beautifulsoup4==4.4.1
> docopt==0.6.2
> irc3==0.9.3.dev0
> requests==2.10.0
> venusian==1.0

I run Python 3.4 on Ubuntu 14.04.

Thank you for your consideration.

**Comment by gawel** [comment]
I'm not able to reproduce the problem. Everything is fine if I use ```pkill -INT -f irc3```

**Comment by gawel** [comment]
Finally got the same problem. But I think it's not related to irc3.
Got it with a really simple script without signals.

After a quick search I found this https://mail.python.org/pipermail/python-bugs-list/2016-January/290450.html
