### ISSUE TITLE
IRCv3.1 SASL authentication support?

### ISSUE THREAD

**Issue by floatingatoll** [gawel/irc3#109]
http://ircv3.net/specs/extensions/sasl-3.1.html

Please consider implementing support for the AUTHENTICATE extension, supported by various networks (e.g. Freenode and Mozilla) as a way to automatically identifying to Nickserv during the initial connection phase without requiring clients to PRIVMSG their credentials.

**Comment by gawel** [comment]
Pull request welcome

**Comment by floatingatoll** [comment]
Apologies, it's beyond my ability to code in this language. Sorry for disturbing.
