### ISSUE TITLE
ping pong

### ISSUE THREAD

**Issue by Awmusic12635** [gawel/irc3#110]
Just started using IRC3 and having an issue where the program keeps thinking it is disconnected (freenode if it matters):

```
INFO irc3.totallynotabot We're waiting a ping for too long. Trying to reconnect...
CRITICAL irc3.totallynotabot connection lost (4350070008): 'No pong reply'
```

However it is not disconnected. This causes it to attempt to reconnect and then ends up making a another connection with a different username.

**Comment by gawel** [comment]
That's weird. I got 2 bot on freenode and never had this problem. Are you sure you do not had 2 processes running ?
