### ISSUE TITLE
Problem importing a pyvenv installed irc3 into a global ipython3

### ISSUE THREAD

**Issue by yuvallanger** [gawel/irc3#111]
`irc3` is installed in the `benny` pyvenv, while `ipython3` was installed to the `yuvallanger` user environment using `python3 -m pip install --user ipython`.

The error:

    (benny) yuvallanger@yankel-Lenovo-G505:~/projects/benny⟫ ipython3
    import irc3
    /home/yuvallanger/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:712: UserWarning: Attempting to work in a virtua
    lenv. If you encounter problems, please install IPython inside the virtualenv.
      warn("Attempting to work in a virtualenv. If you encounter problems, please "
    Python 3.5.2 (default, Jul  5 2016, 12:43:10)
    Type "copyright", "credits" or "license" for more information.
    
    IPython 5.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import irc3
    ---------------------------------------------------------------------------
    DistributionNotFound                      Traceback (most recent call last)
    <ipython-input-1-457396cbab9d> in <module>()
    ----> 1 import irc3
    
    /home/yuvallanger/.virtualenvs/benny/lib/python3.5/site-packages/irc3/__init__.py in <module>()
         12 from . import utils
         13 from . import rfc
    ---> 14 from . import base
         15 from irc3.compat import urlopen
         16 from .compat import text_type
    
    /home/yuvallanger/.virtualenvs/benny/lib/python3.5/site-packages/irc3/base.py in <module>()
         19     version = ''
         20 else:
    ---> 21     version = pkg_resources.get_distribution('irc3').version
         22
         23
    
    /home/yuvallanger/.local/lib/python3.5/site-packages/pkg_resources/__init__.py in get_distribution(dist)
        533         dist = Requirement.parse(dist)
        534     if isinstance(dist, Requirement):
    --> 535         dist = get_provider(dist)
        536     if not isinstance(dist, Distribution):
        537         raise TypeError("Expected string, Requirement, or Distribution", dist)
    
    /home/yuvallanger/.local/lib/python3.5/site-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
        413     """Return an IResourceProvider for the named module or requirement"""
        414     if isinstance(moduleOrReq, Requirement):
    --> 415         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
        416     try:
        417         module = sys.modules[moduleOrReq]
    
    /home/yuvallanger/.local/lib/python3.5/site-packages/pkg_resources/__init__.py in require(self, *requirements)
        941         included, even if they were already activated in this working set.
        942         """
    --> 943         needed = self.resolve(parse_requirements(requirements))
        944
        945         for dist in needed:
    
    /home/yuvallanger/.local/lib/python3.5/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_
    conflicting)
        827                     if dist is None:
        828                         requirers = required_by.get(req, None)
    --> 829                         raise DistributionNotFound(req, requirers)
        830                 to_activate.append(dist)
        831             if dist not in req:
    
    DistributionNotFound: The 'irc3' distribution was not found and is required by the application
    
    In [2]:

**Comment by Zopieux** [comment]
I just tried with a virtualenv for irc3 and a system-wide (`/usr/bin`) ipython and it worked fine.

**Comment by gawel** [comment]
I guess it's fixed
