### ISSUE TITLE
Problems accessing IRC topic 

### ISSUE THREAD

**Issue by mkzero** [gawel/irc3#119]
So I'm currently trying to retrieve and set the topic of a channel but I cannot get my code to work. I've tried requesting the topic with bot.topic(chan) in a cron and then receiving the event with the event decorator and the rfc.RPL_TOPIC but that yielded no results at all.

Is there something I'm missing? I'd happily PR an example after I got a working version for this so others don't run into the same problem.

**Comment by gawel** [comment]
Sorry, I missed this one.

Don't really know what your problem is. Hard to say without a code snippet.

Maybe RPL_TOPIC's regexp is not not correct

Maybe you can give a try to the async way: https://github.com/gawel/irc3/blob/master/irc3/plugins/async.py#L152
Once you have a clean class you should be able to use ```yield from Topic(bot)(channel='#bar', topic='foo')```

Hope this helps

**Comment by gawel** [comment]
This work just fine (at least on freenode):

```python
import irc3
from irc3.plugins.command import command


@irc3.plugin
class TopicPlugin:

    def __init__(self, bot):
        self.bot = bot

    @irc3.event(irc3.rfc.RPL_TOPIC)
    def get_topic(self, channel=None, data=None, **kwargs):
        self.bot.log.warn('Topic for %s is %s', channel, data)

    @command
    def topic(self, bot, target, args):
        """Set topic

        %%topic <topic>...
        """
        if target.is_channel:
            self.bot.topic(target, ' '.join(args['<topic>']))

```

**Comment by gawel** [comment]
Looks like you must also take care of rfc.TOPIC

**Comment by mkzero** [comment]
Okay, thanks for your help and sorry, I think I found my mistake now. I had yields in my event definition without the async.coroutine decorator, which would lead the method to seemingly never be executed.

**Comment by gawel** [comment]
No problem, this issue made me improve that stuff :) See https://github.com/gawel/irc3/commit/20762039557b8b54a7f875baf8c986c19fef2ea8
