### ISSUE TITLE
Command alias support

### ISSUE THREAD

**Issue by TheReverend403** [gawel/irc3#121]
Example: `@command(name='example', aliases=['foo', 'bar'])`

**Comment by gawel** [comment]
Not optimal but you probably can use this already:

```
@command(name='example')
@command(name='foo')
@command(name='bar')
def your command(...):
```

**Comment by TheReverend403** [comment]
I already tried that, it doesn't work. It also creates unnecessary entries in `.help`'s list.

**Comment by TheReverend403** [comment]
Turns out it does work, but you then have to define your command docopts as `%%(command|alias|alias2)` and so on. This is obviously far from idea.

**Comment by gawel** [comment]
Roger. I'll try to add this ASAP but I'm pretty busy those days.
