### ISSUE TITLE
Call /me command

### ISSUE THREAD

**Issue by Bilb** [gawel/irc3#123]
Hi,
Is irc3 able to send /me commands ?

If I do a "/me say hello", and send it with bot.privmsg, the result in an irc client, is a message from the bot like "/me say hello" rather than "* bot say hello"

It looks like the library is escaping the content sent. Is there a way to call the /me command by another way ?

Thanks,
Audric

**Comment by gawel** [comment]
/me does not exist. when you using it in your irc client, what it really send is something like:

```
NOTICE #channel \x01ACTION\x01 bla
```
(totally not verified)

You can send raw lines with whatever you want using ```bot.send_line()``` https://irc3.readthedocs.io/en/latest/irc3.html?#irc3.IrcBot.send_line

I'm not against adding a .action() if you want to provide a PR but it's totally useless to me.

**Comment by Bilb** [comment]
Ok thanks for your help. I've manage to make it work. You were close !
For those looking for the answer :
```
message = "\001ACTION  " + message[4:] + " \001"
self.bot.privmsg(target, message)
```

**Comment by Zopieux** [comment]
Hey I just saw this issue, and this is crazy, but here's my IP, so call `/me` maybe.
