### ISSUE TITLE
Bouncer support? 

### ISSUE THREAD

**Issue by TheReverend403** [gawel/irc3#14]
I'm having a problem with irc3 and ZNC, the problem being that irc3 connects perfectly, but it doesn't join any channels and it doesn't receive or send messages for the channels the bouncer is in, which in theory should also be channels the bot is in due to the way a bouncer works. Is this a bug, or a problem with the way I'm using irc3?

**Comment by johnlage** [comment]
I just tested this on version 0.9.4 of irc3 and connecting to a ZNC instance worked perfectly (ZNC version ZNC 1.7.x-git-591-15ae561)

**Comment by TheReverend403** [comment]
Confirmed, works fine on irc3 0.9.6 and ZNC 1.6.3.
