### ISSUE TITLE
Reload on the fly of module/code

### ISSUE THREAD

**Issue by dummys** [gawel/irc3#149]
Hello,
Thanks for your lib, I love it. Is it possible to reload module or add new module without disconnecting the bot from the IRC network ?
Thanks.

**Comment by Zopieux** [comment]
https://irc3.readthedocs.io/en/latest/search.html?q=reload

**Comment by dummys** [comment]
ok will try, thanks for help !

**Comment by gawel** [comment]
It's maybe doable but will require a lot of code (you need to keep the latest working state etc.) I'd like to avoid this since the reload feature was originally made only to ease development.

**Comment by dummys** [comment]
Ok. I love this feature, it's really cool. thanks for implementing it.
