### ISSUE TITLE
Ability to silence "Invalid arguments." response.

### ISSUE THREAD

**Issue by mattbox** [gawel/irc3#151]
I don't think there's a way to silence the "Invalid arguments." response when someone uses a command incorrectly. I have a plugins setup to ignore some channels from the config, but if someone enters the command incorrectly in the ignored channel "Invalid arguments." is still posted.

The response is called from `plugins/command.py` before the plugin's command function so I added a quick option to the decorator 1a945cf4b94e1f9f8ae8c70d0db40760ebc8ca66 to where it can be set like the the `permissions` or `public` arguments.

```python 
@command(quiet=True)
def w(self, mask, target, args):
    # rest of command....
```
I don't know if the option already exists and I'm missing it or if there's a better solution. I'm not a super experienced with python, so hopefully someone else can help

**Comment by gawel** [comment]
No it doesn't exist. You can provide a PR if you want.

**Comment by mattbox** [comment]
Okay cool, I'll clean it up a bit and submit a PR then.
