### ISSUE TITLE
Docs in other formats(PDF, etc)

### ISSUE THREAD

**Issue by farooqkz** [gawel/irc3#153]
Hi,
How about adding a PDF version(and also other versions like TXT) of documentations to readthedocs?

**Comment by Zopieux** [comment]
https://readthedocs.org/projects/irc3/downloads/

[PDF](https://media.readthedocs.org/pdf/irc3/latest/irc3.pdf) ⋅ [epub](https://readthedocs.org/projects/irc3/downloads/epub/stable/)

**Comment by farooqkz** [comment]
@Zopieux: sorry, I didn't explore well. Just closed this.
