### ISSUE TITLE
Users with formatted vhosts are invisible to the bot's PRIVMSG regex

### ISSUE THREAD

**Issue by TheReverend403** [gawel/irc3#154]
Sorry about the chat content ;)

![screenshot](https://a.pste.pw/IKq.png)

As a result, users with formatted vhosts cannot use anything that relies on a PRIVMSG, such as commands.

**Comment by gawel** [comment]
I don't really understand your screenshot. But irc3 use tolerant regexp (only check for spaces): https://github.com/gawel/irc3/blob/master/irc3/rfc.py#L64

Si this should work with whatever the vhost is. Right ?

**Comment by zack6849** [comment]
@gawel look at the hostmask for the user Cosumu on the right screen, he had formatting codes in his vhost.

The bot wouldn't recognize his messages when he had the vhost but the second he removed it, it did

**Comment by gawel** [comment]
I see. Don't know how to catch those in a regexp. \S is "everything but spaces" So... it should work since color codes are not spaces.

**Comment by gawel** [comment]
If you don't have any clue, I guess it's a wontfix...
