### ISSUE TITLE
irc3.plugins.fifo not work after a long time running

### ISSUE THREAD

**Issue by utopianf** [gawel/irc3#157]
I am writing a irc bot with your great package which enables the message from browser sent to irc channels by using irc3.plugins.fifo.
It works at the first some hours, but after about half a day, I cannot send message from fifo.  

It seems that there are some fifos in /tmp/run/irc3, but it just don't work with irc3.
Is there any limitation with fifos?
 
I am using
Ubuntu 16.04.3 LTS with Python 3.6.2

Thanks!

**Comment by gawel** [comment]
Hm, no. We use this plugin for monthes in my company and never had this problem

**Comment by bacher09** [comment]
Hi. Does sending something to fifo hangs on or it works as usual ? If it hangs, it means, that application have closed fifo (or isn't reading from it). If it works ok, then data probably got stuck in some buffer.
For example, it possible that network is congested or remote server have announced zero TCP window.

Next time when you will face with this issue you can make few checks. First, check or fifo file is still open by bot. You can check it simply by `ls -l /prod/$pid/fd/', you should see links to fifo file.
Also start strace `strace -f -s 1024 -o /tmp/bot_trace.log -p $bot_pid` and try to write data to fifo. After that you can stop strace and check log file. **Also note**, if you are going to publish this log somewhere, first check it contents for passwords and stuff like that. It might contain IRC passwords and stuff like that.

**Comment by utopianf** [comment]
Thank you for your kind suggestion!

I checked `/proc/$pid/fd/` and there are links.
Then I try to strace and get the log as below.

I am not so familiar with Linux that I hardly learn anything from this log.

![image](https://user-images.githubusercontent.com/8581846/36940848-a5179c76-1f90-11e8-8127-e4131d519d0a.png)

**Comment by bacher09** [comment]
I can guess that you have tried to send `test\n` to fifo and fifo is using 13 descriptor. So `/proc/$pid/fd/13` is linked to your fifo. Am I correct ?

If I'm right, then also try to search other appearences of "test\n", maybe bot is sending it, but server ignores it for some reason (debug log also can help with this). Also, try to find descriptors for network connection, and check if they were available for writing. For example, when remote side will announce zero TCP window, socket will be not available for writing. But in that case bot can't send anything to server. 

Also, another one suggestion. You can install library into virtualenv and edit fifo plugin. For example, you can add few prints [here](https://github.com/gawel/irc3/blob/master/irc3/plugins/fifo.py#L89) so you will see that plugin calls `privmsg` or `send_line`.

**Comment by bacher09** [comment]
Also, another one question. Have you send "test\n" two times  ?  Have you edited strace log before making screenshot.

Because it looks like you have send two times input into fifo and bot haven't tried to contact with IRC server at all.

**Comment by utopianf** [comment]
I'm sorry that I forgot to describe what I have done.
It is correct that I used the command `echo 'test' > /tmp/run/irc3/#test_channel` twice.
I will try to find if plugin calls `privmsg` or `send_line`.

Also, I found you decode the line into UTF-8, but the IRC server used ISO-2022-JP. Is it possible to occur some problems?

**Comment by bacher09** [comment]
> Also, I found you decode the line into UTF-8, but the IRC server uses ISO-2022-JP. Is it possible to occur some problems?

It's input encoding, and not server encoding. So it means, that input you pass into fifo will treated as utf8 string. Then, library will try to encode it to correct encoding and deliver to server.

**Comment by bacher09** [comment]
Btw, also you can try to check socket send queue. `sudo netstat -natp` and find bot's socket. If you will see that there is data in `Send-Q` that means that bot have troubles sending data.

**Comment by utopianf** [comment]
Finally, it seems that this problem is from another package which written by myself.
Without it, irc3 works good.

Sorry for the confusion.
