### ISSUE TITLE
Hide commands from `plugins.command`

### ISSUE THREAD

**Issue by lenormf** [gawel/irc3#167]
Hi,

I'm trying to hide some commands from the help message that users don't care about: `ping`, `quote` etc. The administrators know they exist, so I don't care about documenting them publicly.

I tried the following in my configuration file, it didn't hide the command:

```ini
[irc3.plugins.command.ping]

show_in_help_list = false
```

Am I missing something?

**Comment by gawel** [comment]
quote & reconnect are only available in debug mode: https://github.com/gawel/irc3/blob/master/irc3/plugins/command.py#L457

The ping command can't be hidden. This kind of per command configuration is not supported.

show_in_help_list only works with the `@command` decorator: `@command(show_in_help_list=False)`

**Comment by gawel** [comment]
If the only remaining problem is the ping command, we can add a show_in_help_list=False. I've no problem with that. This way no builtin command are available in help by default

(in fact we can also add a show_in_help_list=False to redirect/quote too)

**Comment by lenormf** [comment]
Sounds good, thanks! I'll stay tuned.
