### ISSUE TITLE
Handle several hosts in a configuration file

### ISSUE THREAD

**Issue by lenormf** [gawel/irc3#168]
Hi,

It'd be nice to be able to connect a bot to multiple hosts, without having to duplicate configuration files.

Is that doable?

**Comment by gawel** [comment]
Hm no. A bot instance only manage a connection. But you can easily have more than one instance and make then communicate with a few lines of code. There's an example here: https://github.com/gawel/irc3/blob/master/examples/spy.py

You can use from_argv to load a specific config file then use another `[bot]` section to instanciate another one:
Ini
```
[bot]
host = ...

[bot1]
host = ...
```
Then a few python code:
```
bot = IrcBot.from_argv('aconfig.ini')
bot1 = IrcBot.from_argv('aconfig.ini', **bot.config['bot1])
```
Not tested but should work

**Comment by gawel** [comment]
Maybe it's not that hard to had this. Eg if you have more than one `[bot]` sections then it'll instanciate all sections. I'll have a look

**Comment by lenormf** [comment]
Thanks!
