### ISSUE TITLE
Builtin authentication plugin

### ISSUE THREAD

**Issue by lenormf** [gawel/irc3#169]
Hi,

I see that there's a hook for NickServ authentication in `examples/nickserv.py`, could this be turned into a builtin "auth" plugin loadable directly from the configuration? Other forms of authentication could be provided alongside, e.g. AuthServ on Gamesurge.

Thanks!

**Comment by gawel** [comment]
There's too many different services. It's not possible to cover all of them.
And it usually requires only a few lines of code. So I'm -1 for this.

**Comment by lenormf** [comment]
Alright thanks.
