### ISSUE TITLE
KeyError: irc3.plugins.userlist in new_nick

### ISSUE THREAD

**Issue by TheReverend403** [gawel/irc3#177]
Title says it all, here's the Sentry issue I just got: https://sentry.io/share/issue/761986578fcc48db93a9df31343d92b2/

**Comment by gawel** [comment]
That's really weird. And should never happen. Do you have a bit more context ? Like, is it a special user ? The bot has been disconnected ?

**Comment by TheReverend403** [comment]
Yeah, tends to happen if some network weirdness has happened like the bot timing out or a netsplit occurring.
