### ISSUE TITLE
irc3.plugins.autojoins: join after kick delay

### ISSUE THREAD

**Issue by 676339784** [gawel/irc3#183]
I like irc3's feature in which the "bot will retry to join when kicked" but this has posed one issue: if the bot rejoins too quickly after kicks repeatedly, the bot gets killed. Is there a way to add a delay to auto-rejoin after kick so that this does not happen?

**Comment by gawel** [comment]
No, but maybe you can make on_kick behave like on_err_join https://github.com/gawel/irc3/blob/master/irc3/plugins/autojoins.py#L108

**Comment by 676339784** [comment]
Cool, thank you!
