### ISSUE TITLE
Run in a specific event loop

### ISSUE THREAD

**Issue by Vincysuper07** [gawel/irc3#184]
Hello! I would like to run this IRC client with my Discord bot to make a brigde. I checked the code and it looks like there isn't any way to make the client run in the same loop as the bot. Did I check wrong? If yes, how can I run them in the same loop?

**Comment by gawel** [comment]
Hi, it should work. There's many example on how to run multiple bot instance using one loop https://github.com/gawel/irc3/blob/master/examples/benches.py

I guess from_argv is not for you but check from_config

**Comment by Vincysuper07** [comment]
Okay, thank you.
