### ISSUE TITLE
docopt's option's description and [options] shortcut aren't working

### ISSUE THREAD

**Issue by bad-blue-bull** [gawel/irc3#193]
according docopt's documentation:

> An option's description allows to specify:
> 
>     that some short and long options are synonymous,
>     that an option has an argument,
>     and the default value for an option's argument.
> 

> ...

> "[options]" is a shortcut that allows to avoid listing all options (from list of options with descriptions) in a pattern. For example:
> 
> Usage: my_program [options] <path>
> 
> --all             List everything.
> --long            Long output.
> --human-readable  Display in human-readable format.
> 
> is equivalent to:
> 
> Usage: my_program [--all --long --human-readable] <path>
> 
> --all             List everything.
> --long            Long output.
> --human-readable  Display in human-readable format.
> 
this clearly isn't working in plugin at it's very bad.

**Comment by gawel** [comment]
I'm sorry but I don't understand your issue as this.

**Comment by gawel** [comment]
no feedback
