### ISSUE TITLE
External command output not relayed to IRC channel

### ISSUE THREAD

**Issue by zerodeux** [gawel/irc3#205]
I have a bot with this kind of usage of the "command" plugin :

    [irc3.plugins.shell_command]
    ls = /bin/ls

If I ask the bot to run the command, it runs it (I confirmed it by strace'ing the irc bot, command runs successfully and properly outputs to its pipe), but I can't see the command output on the IRC channel where the bot lives.

Internal commands (help, uptime) do work properly.

This bug appeared while upgrading from Debian 10/Python 3.7.3 to Debian 11/Python 3.9.2 (with its virtualenv rebuilt from scratch after the Python upgrade).

**Comment by gawel** [comment]
It's a bug. Introduced when removing some deprecation warning https://github.com/gawel/irc3/commit/4f15a84ca93378c21c573343f336ff562279ddc1#diff-34dc3397886ac95692c5bae9c8f065814a80246823eb717946bb1e0cfaac1bbdL94
