### ISSUE TITLE
Docopt command options_first flag, parsing negative numbers

### ISSUE THREAD

**Issue by CrystalDave** [gawel/irc3#37]
For context, I'm working on porting a dicebot to use this library. Triggering this issue is that I'm attempting to create a command with a simple +/- numerical modifier. (example: `!apoc -2`, `!apoc +1`)

I've tracked this down to how IRC3 uses Docopt for command parsing, & how Docopt has an issue with using '-' to signal option commands. (docopt/docopt#158)

In the Docopt issue linked, there's a pair of workarounds provided which could work here:
Adding support for the `options_first=True` flag (added in Docopt 0.6.0), and adding the ability to modify an argument string as it comes in to prefix`--`.

I'm currently looking into how feasible this would be in the existing codebase, but at the least, adding the ability to flip the `options_first` flag would be an improvement.

**Comment by gawel** [comment]
As I understand you need this option per command, not globally ?

**Comment by CrystalDave** [comment]
That'd be ideal. (I might be able to rework things to survive with a global `options_first` flag, but per-command would be the most flexible)

**Comment by gawel** [comment]
Already done, then. See the referenced commit (https://github.com/gawel/irc3/commit/76cc523036f91cd7cd96258da1debc56869861cc)
