### ISSUE TITLE
Option to not keep trying new nick

### ISSUE THREAD

**Issue by meshy** [gawel/irc3#38]
I'm trying to write a client, but am finding the behaviour when the `nick` command fails a little frustrating.

As it currently stands, when the [`badnick`](https://github.com/gawel/irc3/blob/93a40f7c1acebbadf2cbd66be1a1805177703a70/irc3/plugins/core.py#L100-L106) method is called, a callback is set to retry the attempt again in 30 seconds. If the user picks a new nick in the interim (potentially a long time, as this callback is set repeatedly), and then the clashing nick disconnects, the user will get renamed, despite having already selected a new nick.

I would like to forego this behaviour in my client but, as far as I can tell, I cannot remove this one line without duplicating the whole module into my program, as if I were to subclass the module, the old method would already have been registered as an event.

Have I missed something --- is there a cleaner way for me to do this?

If there is no obvious way to fix this at the moment, I wonder if it would be desirable for me to refactor this module in some way to allow for easier extension, and if there are any suggestions for how I might proceed?

Thanks for taking the time to read this --- sorry that the report is little long!

**Comment by meshy** [comment]
I tried duplicating the module as a stopgap, but that doesn't even work, because use of that module is [hard-coded into the `command` module](https://github.com/gawel/irc3/blob/76cc523036f91cd7cd96258da1debc56869861cc/irc3/plugins/command.py#L188).

**Comment by gawel** [comment]
I just pushed something for you:

https://github.com/gawel/irc3/commit/f1d5aace975bf26eaad68d148a00eb3cbf13e596

So you'll be able to cancel the retry:

```
handle = bot.get_plugin('irc3.plugins.core').nick_handle
if handle is not None:
    handle.cancel()
```

**Comment by meshy** [comment]
That's very considerate, thank you `:)` I'll give it a try as soon as I am able.

**Comment by gawel** [comment]
Guess it work

**Comment by meshy** [comment]
Sorry I forgot about this. I decided to take a different direction, as I wasn't really sure where best to watch for this value. Thanks for your help, though.
