### ISSUE TITLE
A command's name should be able to be different than the method's name

### ISSUE THREAD

**Issue by metathink** [gawel/irc3#43]
It could be usefull to avoid some names collisions, for example to be able to create a !reload command with the new plugin reload system.

Exemple:

```python
@command(name='reload', permission='admin')
def cmd_reload(self, mask, target, args):
    """
    Reload a plugin on the fly
    
    %%reload <plugins>...
    """
    self.bot.reload(*args['<plugins>'])
```

I made some changes locally in irc3/plugins/command.py and it seems to work, but I created a gist instead a pull request because I was not sure about the changes: https://gist.github.com/metathink/4a00a1d7bc9901781e08

**Comment by thomwiggers** [comment]
It would be better to create a pull request, because that way we can discuss the code and have any comments show up in the overview of the issue. Also, Travis would automatically run the tests.

Otherwise the changes seem sensible to me.

**Comment by gawel** [comment]
It's already done https://github.com/gawel/irc3/pull/44

This don't break anything. The name parameter is not required.
