### ISSUE TITLE
utils.split_message strips control characters

### ISSUE THREAD

**Issue by valhallasw** [gawel/irc3#46]
split_message uses .strip(), which removes whitespace. Unfortunately, '\x1f', which is used to set  underline, is the 'unit seperator' and thus counts as whitespace. This means a message that starts with underlined text does not show up as underlined.

This is also true for '\x1d' (italic). '\x02' (bold), '\x03' (color), '\x0f' (reset) and '\x16' (reverse colors) are not whitespace.

**Comment by gawel** [comment]
I see your point, but I don't really see how to solve this.

I guess the best options is to split messages by yourself

What's your use case ?

**Comment by valhallasw** [comment]
The use case is starting a line with an underlined word. Even if it is not
too long,  the underline marker will be stripped.

There are multiple solutions, but the easiest one is probably to only strip
ascii spaces (and maybe tabs) instead of all white space. Stripping
everything except for these two is probably hard. Alternatively, just
stripping from the right should also work.

**Comment by gawel** [comment]
I'm sorry, but I still need an explanation. For me those chars are not stripped:

```
>>>  '\x1d \x1d'.strip()
'\x1d \x1d'
```

Can you provide an example ?

**Comment by valhallasw** [comment]
It might depend on Python version (and with that Unicode version). For me:
```
(py-wikibugs2)tools.wikibugs@tools-login:~/wikibugs2-dev$ python
Python 3.4.0 (default, Apr 28 2014, 12:05:20)
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "\x1d \x1f".strip()
''
```

I get the same behavior with 2.6, 2.7, and 3.3, though. Maybe it was changed in 3.5? I tested with an alpha release (which did strip) but not with the final.

**Comment by gawel** [comment]
Got it. I was testing with 2.7.6. Does not have this behavior. Weird.
