### ISSUE TITLE
bin/ folder is missing

### ISSUE THREAD

**Issue by thomwiggers** [gawel/irc3#47]
Stuff like the Makefile depend on scripts in a folder called `bin/`. However, this folder is not part of the repository. Could it be added?

**Comment by gawel** [comment]
That's because I'm using buildout. It generate bin/*. Scripts are just entry points.

Just run:

```
pip install zc.buildout
buildout
```

Or:

```
python bootstrap.py
bin/buildout
```

I don't want to add them to the repo because those extra scripts are totally useless/can be confusing for end users.

**Comment by thomwiggers** [comment]
Not having a functioning Makefile (I was testing a tweak to the `rfc14xx.txt`) is also confusing…

**Comment by gawel** [comment]
Yes, totally right. Maybe those entry points can be generated iif you're in dev mode. by running python setup develop or something. A HOWTO hack section in the docs can help too

**Comment by thomwiggers** [comment]
Shouldn't buildout also be mentioned in `hack.rst`? Also, it might be worthwhile to move the file to the root as `CONTRIBUTING` as that will make Github show it along the 'new issue' and 'new pull request' forms: https://github.com/blog/1184-contributing-guidelines

I'm not sure if that works for `.rst` though...

**Comment by gawel** [comment]
I guess it work https://github.com/search?q=contributing.rst&type=Code

I'm not sure about buildout. It's no longer required so will it be useful ?

**Comment by thomwiggers** [comment]
Wouldn't it in that case be better to remove stuff that depends on it, like the (relevant parts of the) Makefile?
