### ISSUE TITLE
IRC Bot for python 3

### ISSUE THREAD

**Issue by kiwiheretic** [gawel/irc3#49]
I am the author of an existing IRC Bot project which is for python 2.7 and currently lacks a complete strategy for moving to python 3. The project is at https://github.com/kiwiheretic/logos-v2 and has a wiki at https://github.com/kiwiheretic/logos-v2/wiki.  I am looking at your project as a possible migration option as it would be easier for me to just concentrate on plugins rather than have to maintain an entire bot. Also I wish to avoid reinventing wheels that I don't have to when I eventually move to python 3.  (Especially seeing that Twisted seems unsupported on Python 3).    However there are some things about your project I am not clear about and hopefully you will be able to answer them for me.

* I see you have some kind of permissions (which you appear to call guards) that restrict certain commands to certain users.  How does this work in practice and what kind of authentication mechanism do you use?  (ie Nickserv, logging into bot, etc)
* Can your bot operate in more than one room with different plugins active for certain rooms and not in others?
* Is there any mechanism for one plugin to pass data to another plugin?  (Yeah, I know this sounds strange but I am thinking in terms of some kind of message broadcasting system where each plugin can opt to listen or not listen.  I have one plugin that listens to data from one plugin and uses a wordpress plugin to log the data.)
* How do you deal with the blocking problem when interacting with web services like twitter etc?

Thanking you, in advance, for your time.

**Comment by gawel** [comment]
On Thu, Mar 05, 2015 at 08:21:32PM -0800, kiwiheretic wrote:
> * I see you have some kind of permissions (which you appear to call guards) that restrict certain commands to certain users.  How does this work in practice and what kind of authentication mechanism do you use?  (ie Nickserv, logging into bot, etc)

A guard is a class that take the bot as argument and implement a __call__
method that check is the user is allowed.

There is two builtin policies: everything is allowed vs mask based policy
(mean only allowed ircs mask can run a command) See https://github.com/gawel/irc3/blob/master/irc3/plugins/command.py#L133

> * Can your bot operate in more than one room with different plugins active for certain rooms and not in others?

No, plugin has nothing related to channels

> * Is there any mechanism for one plugin to pass data to another plugin?  (Yeah, I know this sounds strange but I am thinking in terms of some kind of message broadcasting system where each plugin can opt to listen or not listen.  I have one plugin that listens to data from one plugin and uses a wordpress plugin to log the data.)

Not really. But the bot.get_plugin(PluginClass) method allow you to access a
plugin instance.

> * How do you deal with the blocking problem when interacting with web services like twitter etc?
> 

Since irc3 use asyncio you can always use yield from loop.run_in_executor(None,
your_blocking_method) to run blocking code. This will run the method in a
thread. It's even better if you use asyncio based libraries like aiohttp

**Comment by kiwiheretic** [comment]
So am I correct in assuming that your authentication system is mask based?  (That is nick!user@host with the possibility of wildcards.)  I can see that might if someone uses different nicks or several hosts.  Is that the only authentication mechanism that the bot uses?  In other words does it have any concept of username/password log in to the bot?

**Comment by gawel** [comment]
The auth system is pluggable and it shouldn't be hard to implement a password based auth. I just don't need it. So you'll have to write you're own.
