### ISSUE TITLE
irc3 and celery

### ISSUE THREAD

**Issue by lucacapacci** [gawel/irc3#50]
hi, I'm executing an irc3 bot inside a celery task. The bot correctly connects to the server but it doesn't auto connect to the channels. And it behaves in a strange way with my plugin (a plugin to print received messages): it works for the first few messages received, then nothing happens.
And it doesn't answer to pings.

If I run my code directly and not inside a celery task it works perfectly.

**Comment by gawel** [comment]
I don't really have a clue without more informations.  Is your code public ?

**Comment by gawel** [comment]
Got an idea. Maybe the bot is intanciated in a thread and run in another.
You can try to debug this with:

print(asyncio.get_event_loop() is bot.loop)

Should print True

**Comment by lucacapacci** [comment]
I think I solved the problem, it was my fault. Thanks for your help!
