### ISSUE TITLE
215 - RPL_STATSILINE - redefinition of group name 'host'

### ISSUE THREAD

**Issue by wapiflapi** [gawel/irc3#68]
The regex for `RPL_STATSILINE` is:
```py
 "I (?P<host>\S+) . (?P<host>\S+) (?P<port>\S+) (?P<class>\S+)")
```

It's an error to have both groups named host, this can't possibly work.

**Comment by gawel** [comment]
You're right. This is autogenerated and need to be fixed somewhere around https://github.com/gawel/irc3/blob/master/irc3/_parse_rfc.py#L96

**Comment by wapiflapi** [comment]
Along the same lines:
```
RPL_TRACEUNKNOWN
multiple repeat in ^:(?P<srv>\S+) 203 (?P<me>\S+) ???? (?P<class>\S+) [(?P<clientip>\S+)]
```

;-) will check if I have some time to fix this later this week.

**Comment by gawel** [comment]
I've fixed the first one but I don't see the problem for RPL_TRACEUNKNOWN

**Comment by wapiflapi** [comment]
I think `????` isn't legal in a regex. `?` is supposed to mean `once or not` so repeating it several times like that confuses it and I'm getting an exception `multiple repeat`.

**Comment by gawel** [comment]
Ok, fixed too. Thanks for the reports
