### ISSUE TITLE
human plugin causes errors on windows

### ISSUE THREAD

**Issue by Felk** [gawel/irc3#73]
because it uses the unix command-line (wget, grep etc.). see https://github.com/gawel/irc3/blob/4d99b5fb5f9d36d36217b0f768f7c2005dd9ab6a/irc3/plugins/human.py#L62

**Comment by gawel** [comment]
This is just to initialize a file with a few random sentences. It will work if you create the file yourself

**Comment by gawel** [comment]
And the service is broken http://www.iheartquotes.com/
