### ISSUE TITLE
Trying to send too large messages may result in RevQ exceeded

### ISSUE THREAD

**Issue by thomwiggers** [gawel/irc3#76]
Due to circumstances my bot today rendered too large responses, which led to it getting killed for RevQ exceeded. It'd probably be better if irc3 would drop those messages or snip them, probably while printing a warning or something like that.

Why fix this in irc3 and not in the offending plugin? It seems like this would be an issue that could potentially and unexpectedly affect a lot of different plugins, for example if you're consuming an API which suddenly returns unexpectedly large results.

**Comment by gawel** [comment]
have you tried using bot.call_many('privmsg', [(nick, msg), (nick, msg)...]) ? This will send messages with a delay

**Comment by thomwiggers** [comment]
No, I meant for the case where you (accidentally) do:

    bot.privmsg(target, 'foobar'*10000)

**Comment by gawel** [comment]
maybe using call_many here: https://github.com/gawel/irc3/blob/master/irc3/__init__.py#L181 if len(messages) > config.max_lines can be enough then. Possibly max_lines can be retrieve from server config

**Comment by gawel** [comment]
hm, ok, looks like just a small bug. utils.split_message() do not split the messages if it does not contains spaces. I guess this function can be improved
