### ISSUE TITLE
Example code for DCC receive

### ISSUE THREAD

**Issue by dsan** [gawel/irc3#81]
Is there example code for a bot which is capable to receive DCC file transfers?
That would be really helpful.

**Comment by gawel** [comment]
I don't think so. But it's simple: you'll get a CTCP event (see irc3.rfc.CTCP) with the ip / port to connect to and the file offered (maybe its size). Parse those args and use ```conn = yield from self.bot.dcc_get()``` See https://irc3.readthedocs.org/en/latest/irc3.html?highlight=dcc_get#irc3.IrcBot.dcc_get

**Comment by gawel** [comment]
dcc implementation was broken with python 3.5. It's now fixed. To solve that I needed a real life example so you now got one available at https://github.com/gawel/irc3/blob/master/examples/dcc_send_and_get.py

**Comment by dsan** [comment]
Thank you very much. Will get to give this more time within the upcoming week :+1:
